// <auto-generated />
using System;
using Fox.TaskFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fox.TaskFlow.Infrastructure.Migrations
{
    [DbContext(typeof(TaskFlowDbContext))]
    partial class TaskFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Fox.TaskFlow.Infrastructure.Data.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Install required tools and configure the development environment for the new project. This includes IDE setup, database tools, and version control configuration.",
                            DueDate = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Title = "Setup development environment",
                            UpdatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create a secure authentication system with JWT tokens, password hashing, and role-based authorization. Include login, logout, and password reset functionality.",
                            DueDate = new DateTime(2026, 3, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Title = "Implement user authentication",
                            UpdatedAt = new DateTime(2026, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create entity relationship diagrams and design the database schema for all application entities. Consider normalization, indexes, and performance optimization.",
                            DueDate = new DateTime(2026, 3, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Created",
                            Title = "Design database schema",
                            UpdatedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Document all REST API endpoints with OpenAPI/Swagger specifications. Include request/response examples, authentication requirements, and error codes.",
                            Status = "Created",
                            Title = "Write API documentation",
                            UpdatedAt = new DateTime(2026, 3, 1, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Integration with the old payment provider that is being phased out. This task was cancelled due to business decision to skip the legacy system.",
                            DueDate = new DateTime(2026, 3, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            Title = "Implement legacy payment gateway",
                            UpdatedAt = new DateTime(2026, 3, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
